name: rebuild-index
on:
  push:
    branches:
      - master

permissions:
  checks: write
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: sigoden/install-binary@v1
        with:
          repo: sm-pkg/sm-pkg
          token: ${{ github.token }}

      # - name: install sm-pkg
      #   run: |
      #     wget https://github.com/sm-pkg/sm-pkg/releases/download/v0.1.0/sm-pkg_Linux_x86_64.tar.gz -o sm-pkg.tar.gz
      #     tar -xzf sm-pkg.tar.gz
      #     chmod +x sm-pkg
      #     mv sm-pkg /usr/local/bin/sm-pkg

      - uses: actions/checkout@v5

      - name: "Run sm-pkg build-index"
        run: sm-pkg build-index

      - name: "Commit changes"
        run: |
          git config --global user.name 'github actions'
          git config --global user.email 'github-actions@github.com'
          git commit -a -m "Rebuild index" || echo "No changes to commit"
          git push
