---
name: "yaml linter"
on:
  - pull_request
  - push

permissions:
  contents: read
  pull-requests: write

jobs:
  yamllint:
    name: "yaml linter"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v6

      - name: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v4
        with:
          comment: true
          json_schema: "plugin.schema.json"
          yaml_as_json: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          exclude_file: ".yamlignore"

      - name: "validate schema"
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: "*/plugin.yaml"
          yamllint_strict: true
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
