---
name: "yaml linter"
on:
  - pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  yamllint:
    name: "yamllint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v4
        with:
          comment: true
          json_schema: "https://raw.githubusercontent.com/sm-pkg/sm-pkg/refs/heads/master/schema/plugin.json"
          yaml_as_json: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          exclude_file: index.yaml

      - name: "Yamllint"
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: "*/plugin.yaml"
          yamllint_strict: true
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
